<Page>:
    GridLayout:

        cols:1
        id: main
        Button:
            text: "click"
            on_press: root.show()
        ScrollView:
            GridLayout:
                cols:3
                size_hint_y:None
                spacing:20,20
                id: defs
                height:self.minimum_height
            

                
        # Label:
        #     text: 'Some textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome textSome texts'
        #     text_size: self.width, None
        #     size_hint_y: None
            # height: self.texture_size[1]
<RootWidget>:
    Page:
        name:"page"
